// Garden gamification component
import { state } from '../utils/state.js';
import { saveState } from '../utils/storage.js';
import { showToast } from '../utils/helpers.js';

function checkGardenDecay(){if(state.garden.isPaused&&state.garden.pauseUntil){if(new Date()>=new Date(state.garden.pauseUntil)){state.garden.isPaused=false;state.garden.pauseUntil=null;saveState();}}if(state.garden.isPaused)return false;if(!state.garden.lastActivityDate)return false;const now=new Date();const lastActivity=new Date(state.garden.lastActivityDate);const hoursSince=(now-lastActivity)/(1000*60*60);if(hoursSince>=72){const daysPassed=Math.floor(hoursSince/24);const levelsToLose=Math.min(2,Math.floor((daysPassed-3)/3)+1);const currentLevel=getGardenLevel(state.garden.points);if(levelsToLose>0&&currentLevel>0){const targetLevel=Math.max(0,currentLevel-levelsToLose);const levelPoints=[0,21,51,101,201,500];state.garden.points=Math.max(levelPoints[targetLevel],0);state.garden.level=targetLevel;saveState();return true;}}return hoursSince>=24;}
function addGardenPoints(points,activityName){checkGardenDecay();const wasWithered=state.garden.lastActivityDate&&(new Date()-new Date(state.garden.lastActivityDate))/(1000*60*60)>=24;const oldLevel=getGardenLevel(state.garden.points);state.garden.points+=points;state.garden.lastActivityDate=new Date().toISOString();const newLevel=getGardenLevel(state.garden.points);state.garden.level=newLevel;saveState();updateGardenBadge();let message='';if(wasWithered){message='🌱 Pianta riannaffiata! +'+points+' punti';showToast(message);setTimeout(()=>showToast('💚 Bonus recupero: +50% punti per 24h!'),1500);}else if(newLevel>oldLevel){message='🎉 LIVELLO '+newLevel+'! '+getGardenName(newLevel)+' (+'+points+' pt)';showToast(message);}else{message='✨ +'+points+' punti! '+getGardenEmoji(newLevel,false)+' '+state.garden.points+' pt';showToast(message);}}
function pauseGarden(days){state.garden.isPaused=true;const until=new Date();until.setDate(until.getDate()+days);state.garden.pauseUntil=until.toISOString();saveState();updateGardenBadge();showToast('🌙 Pianta in pausa per '+days+' giorni');}
function resumeGarden(){state.garden.isPaused=false;state.garden.pauseUntil=null;saveState();updateGardenBadge();showToast('🌱 Pausa terminata! Bentornato!');}
function updateGardenBadge(){updateMainButton();}
function updateMainButton(){const emojiEl=document.getElementById('mainGardenEmoji');const levelEl=document.getElementById('mainGardenLevel');const pointsEl=document.getElementById('mainGardenPoints');const progressEl=document.getElementById('mainGardenProgressFill');const pauseBtn=document.getElementById('gardenPauseBtn');if(!emojiEl||!levelEl||!pointsEl||!pauseBtn)return;const isWithered=checkGardenDecay();const level=getGardenLevel(state.garden.points);const emoji=getGardenEmoji(level,isWithered&&!state.garden.isPaused);const name=getGardenName(level);const points=state.garden.points;const levelPoints=[0,21,51,101,201,500];const nextLevel=Math.min(level+1,5);const pointsToNext=levelPoints[nextLevel];const prevLevelPoints=levelPoints[level];const progressInLevel=points-prevLevelPoints;const pointsNeededForLevel=pointsToNext-prevLevelPoints;const progressPercent=level>=5?100:Math.min(100,(progressInLevel/pointsNeededForLevel)*100);emojiEl.textContent=emoji;levelEl.textContent='Lv '+level+' • '+name;pointsEl.textContent=level>=5?points+' punti • Livello massimo!':points+' / '+pointsToNext+' punti al prossimo livello';if(progressEl)progressEl.style.width=progressPercent+'%';if(state.garden.isPaused){pauseBtn.textContent='▶️';pauseBtn.onclick=(e)=>{e.stopPropagation();resumeGarden();};}else{pauseBtn.textContent='⏸️';pauseBtn.onclick=(e)=>{e.stopPropagation();showGardenPauseModal();};}}
function updateHomeStats(){const streakEl=document.getElementById('statStreak');const totalEl=document.getElementById('statTotal');if(!streakEl||!totalEl)return;const streak=calculateStreak();const total=state.history.length;streakEl.textContent=streak;totalEl.textContent=total;}
function calculateStreak(){if(state.history.length===0)return 0;const sortedHistory=[...state.history].sort((a,b)=>new Date(b.date)-new Date(a.date));let streak=0;let currentDate=new Date();currentDate.setHours(0,0,0,0);for(const entry of sortedHistory){const entryDate=new Date(entry.date);entryDate.setHours(0,0,0,0);const diffDays=Math.floor((currentDate-entryDate)/(1000*60*60*24));if(diffDays===streak||diffDays===streak+1){if(diffDays===streak+1)streak++;currentDate=new Date(entryDate);}else{break;}}return streak;}
function updateHomeInsights(){const previewEl=document.getElementById('homeInsightsPreview');const listEl=document.getElementById('homeInsightsList');if(!previewEl||!listEl)return;const insights=getPersonalInsights();if(!insights||state.history.length<3){previewEl.style.display='none';return;}previewEl.style.display='block';let html='';if(insights.recentSuccess){const perc=Math.round(insights.recentSuccess.rate*100);const emoji=perc>=70?'🎉':perc>=50?'💪':'📈';html+='<div class="home-insight-item"><span class="home-insight-emoji">'+emoji+'</span><span>'+perc+'% di successo negli ultimi 7 giorni</span></div>';}if(insights.bestFeeling&&insights.bestFeeling.count>=2){html+='<div class="home-insight-item"><span class="home-insight-emoji">⭐</span><span>Per te funziona quando ti senti '+feelings.find(f=>f.id===insights.bestFeeling.feeling)?.label.toLowerCase()+'</span></div>';}if(insights.temporalPatterns&&insights.temporalPatterns.bestDay){const days=['domenica','lunedì','martedì','mercoledì','giovedì','venerdì','sabato'];html+='<div class="home-insight-item"><span class="home-insight-emoji">📅</span><span>Il tuo giorno migliore: '+days[insights.temporalPatterns.bestDay.day]+'</span></div>';}listEl.innerHTML=html||'<div class="home-insight-item"><span class="home-insight-emoji">✨</span><span>Continua così per sbloccare insights personalizzati!</span></div>';}
function updateHomeScreen(){setGreeting();updateMainButton();updateHomeStats();updateHomeInsights();}
function toggleFabMenu(){const menu=document.getElementById('fabMenu');if(!menu)return;menu.classList.toggle('open');}
function showGardenPauseModal(){if(confirm('Vuoi mettere in pausa il giardino?\n\nLa tua pianta non appassirà per 7 giorni.\nUtile quando hai bisogno di una pausa dall\'app.')){pauseGarden(7);}}
const taskCategories={studio:['studiare','esame','lezione','compiti','tesi','scuola','università','corso','materia','storia','matematica','fisica','chimica'],lavoro:['email','meeting','report','progetto','chiamata','lavoro','riunione','presentazione','deadline','documento','cliente'],casa:['pulizie','pulire','lavare','stirare','cucinare','spesa','casa','cucina','bagno','camera','stanza','piatti','biancheria','bucato'],sociale:['uscire','amici','festa','compleanno','chiamare','sociale','cena','aperitivo','evento','appuntamento'],cura:['doccia','vestirsi','medicine','dentista','sport','palestra','correre','yoga','meditare','dormire'],admin:['bollette','banca','documenti','tasse','prenotare','email','modulo','pratica','appuntamento','telefonata']};
function detectTaskCategory(taskName){const t=taskName.toLowerCase();for(const[cat,keywords]of Object.entries(taskCategories)){if(keywords.some(k=>t.includes(k)))return cat;}return 'altro';}
function normalizeTaskName(name){return name.toLowerCase().trim().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');}
function updateTaskDatabase(taskName,category,feeling,trigger,intensity,strategyUsed,completed){if(!taskName)return;const taskId=normalizeTaskName(taskName);if(!state.tasks[taskId]){state.tasks[taskId]={name:taskName,category:category,firstSeen:new Date().toISOString(),lastMentioned:new Date().toISOString(),timesBlocked:0,timesResolved:0,feelings:{},triggers:{},strategies:{},avgIntensity:0,totalIntensity:0,count:0};}const task=state.tasks[taskId];task.lastMentioned=new Date().toISOString();task.count++;task.totalIntensity+=intensity;task.avgIntensity=(task.totalIntensity/task.count).toFixed(1);task.timesBlocked++;if(completed)task.timesResolved++;task.feelings[feeling]=(task.feelings[feeling]||0)+1;task.triggers[trigger]=(task.triggers[trigger]||0)+1;if(strategyUsed){if(!task.strategies[strategyUsed])task.strategies[strategyUsed]={used:0,completed:0};task.strategies[strategyUsed].used++;if(completed)task.strategies[strategyUsed].completed++;}saveState();}
function getBestStrategyForTask(taskId){const task=state.tasks[taskId];if(!task||!task.strategies)return null;let best=null;let bestRate=0;for(const[stratName,stats]of Object.entries(task.strategies)){if(stats.used<2)continue;const rate=stats.completed/stats.used;if(rate>bestRate){bestRate=rate;best={name:stratName,rate:rate,used:stats.used};}}return best;}

// Personal Insights & Adaptive Learning Functions
function getPersonalStrategyStats(){
  const stats={};
  state.history.forEach(h=>{
    if(h.strategyUsed){
      if(!stats[h.strategyUsed])stats[h.strategyUsed]={used:0,completed:0};
      stats[h.strategyUsed].used++;
      if(h.strategyCompleted)stats[h.strategyUsed].completed++;
    }
  });
  return Object.entries(stats)
    .filter(([,s])=>s.used>=2)
    .map(([name,s])=>({name,used:s.used,completed:s.completed,rate:s.completed/s.used}))
    .sort((a,b)=>b.rate-a.rate||b.used-a.used);
}

function getGardenLevel(points){if(points>=500)return 5;if(points>=201)return 4;if(points>=101)return 3;if(points>=51)return 2;if(points>=21)return 1;return 0;}
function getGardenEmoji(level,withered){const emojis=['🌱','🌿','🪴','🌳','🌲','🌸'];if(withered&&level>0)return'🍂';return emojis[level]||'🌱';}
function getGardenName(level){const names=['Germoglio','Piantina','Pianta giovane','Albero','Albero maestoso','Albero fiorito'];return names[level]||'Germoglio';}
function checkGardenDecay(){if(state.garden.isPaused&&state.garden.pauseUntil){if(new Date()>=new Date(state.garden.pauseUntil)){state.garden.isPaused=false;state.garden.pauseUntil=null;saveState();}}if(state.garden.isPaused)return false;if(!state.garden.lastActivityDate)return false;const now=new Date();const lastActivity=new Date(state.garden.lastActivityDate);const hoursSince=(now-lastActivity)/(1000*60*60);if(hoursSince>=72){const daysPassed=Math.floor(hoursSince/24);const levelsToLose=Math.min(2,Math.floor((daysPassed-3)/3)+1);const currentLevel=getGardenLevel(state.garden.points);if(levelsToLose>0&&currentLevel>0){const targetLevel=Math.max(0,currentLevel-levelsToLose);const levelPoints=[0,21,51,101,201,500];state.garden.points=Math.max(levelPoints[targetLevel],0);state.garden.level=targetLevel;saveState();return true;}}return hoursSince>=24;}
function addGardenPoints(points,activityName){checkGardenDecay();const wasWithered=state.garden.lastActivityDate&&(new Date()-new Date(state.garden.lastActivityDate))/(1000*60*60)>=24;const oldLevel=getGardenLevel(state.garden.points);state.garden.points+=points;state.garden.lastActivityDate=new Date().toISOString();const newLevel=getGardenLevel(state.garden.points);state.garden.level=newLevel;saveState();updateGardenBadge();let message='';if(wasWithered){message='🌱 Pianta riannaffiata! +'+points+' punti';showToast(message);setTimeout(()=>showToast('💚 Bonus recupero: +50% punti per 24h!'),1500);}else if(newLevel>oldLevel){message='🎉 LIVELLO '+newLevel+'! '+getGardenName(newLevel)+' (+'+points+' pt)';showToast(message);}else{message='✨ +'+points+' punti! '+getGardenEmoji(newLevel,false)+' '+state.garden.points+' pt';showToast(message);}}
function pauseGarden(days){state.garden.isPaused=true;const until=new Date();until.setDate(until.getDate()+days);state.garden.pauseUntil=until.toISOString();saveState();updateGardenBadge();showToast('🌙 Pianta in pausa per '+days+' giorni');}
function resumeGarden(){state.garden.isPaused=false;state.garden.pauseUntil=null;saveState();updateGardenBadge();showToast('🌱 Pausa terminata! Bentornato!');}
function updateGardenBadge(){updateMainButton();}
function updateMainButton(){const emojiEl=document.getElementById('mainGardenEmoji');const levelEl=document.getElementById('mainGardenLevel');const pointsEl=document.getElementById('mainGardenPoints');const progressEl=document.getElementById('mainGardenProgressFill');const pauseBtn=document.getElementById('gardenPauseBtn');if(!emojiEl||!levelEl||!pointsEl||!pauseBtn)return;const isWithered=checkGardenDecay();const level=getGardenLevel(state.garden.points);const emoji=getGardenEmoji(level,isWithered&&!state.garden.isPaused);const name=getGardenName(level);const points=state.garden.points;const levelPoints=[0,21,51,101,201,500];const nextLevel=Math.min(level+1,5);const pointsToNext=levelPoints[nextLevel];const prevLevelPoints=levelPoints[level];const progressInLevel=points-prevLevelPoints;const pointsNeededForLevel=pointsToNext-prevLevelPoints;const progressPercent=level>=5?100:Math.min(100,(progressInLevel/pointsNeededForLevel)*100);emojiEl.textContent=emoji;levelEl.textContent='Lv '+level+' • '+name;pointsEl.textContent=level>=5?points+' punti • Livello massimo!':points+' / '+pointsToNext+' punti al prossimo livello';if(progressEl)progressEl.style.width=progressPercent+'%';if(state.garden.isPaused){pauseBtn.textContent='▶️';pauseBtn.onclick=(e)=>{e.stopPropagation();resumeGarden();};}else{pauseBtn.textContent='⏸️';pauseBtn.onclick=(e)=>{e.stopPropagation();showGardenPauseModal();};}}
function updateHomeStats(){const streakEl=document.getElementById('statStreak');const totalEl=document.getElementById('statTotal');if(!streakEl||!totalEl)return;const streak=calculateStreak();const total=state.history.length;streakEl.textContent=streak;totalEl.textContent=total;}
function calculateStreak(){if(state.history.length===0)return 0;const sortedHistory=[...state.history].sort((a,b)=>new Date(b.date)-new Date(a.date));let streak=0;let currentDate=new Date();currentDate.setHours(0,0,0,0);for(const entry of sortedHistory){const entryDate=new Date(entry.date);entryDate.setHours(0,0,0,0);const diffDays=Math.floor((currentDate-entryDate)/(1000*60*60*24));if(diffDays===streak||diffDays===streak+1){if(diffDays===streak+1)streak++;currentDate=new Date(entryDate);}else{break;}}return streak;}
function updateHomeInsights(){const previewEl=document.getElementById('homeInsightsPreview');const listEl=document.getElementById('homeInsightsList');if(!previewEl||!listEl)return;const insights=getPersonalInsights();if(!insights||state.history.length<3){previewEl.style.display='none';return;}previewEl.style.display='block';let html='';if(insights.recentSuccess){const perc=Math.round(insights.recentSuccess.rate*100);const emoji=perc>=70?'🎉':perc>=50?'💪':'📈';html+='<div class="home-insight-item"><span class="home-insight-emoji">'+emoji+'</span><span>'+perc+'% di successo negli ultimi 7 giorni</span></div>';}if(insights.bestFeeling&&insights.bestFeeling.count>=2){html+='<div class="home-insight-item"><span class="home-insight-emoji">⭐</span><span>Per te funziona quando ti senti '+feelings.find(f=>f.id===insights.bestFeeling.feeling)?.label.toLowerCase()+'</span></div>';}if(insights.temporalPatterns&&insights.temporalPatterns.bestDay){const days=['domenica','lunedì','martedì','mercoledì','giovedì','venerdì','sabato'];html+='<div class="home-insight-item"><span class="home-insight-emoji">📅</span><span>Il tuo giorno migliore: '+days[insights.temporalPatterns.bestDay.day]+'</span></div>';}listEl.innerHTML=html||'<div class="home-insight-item"><span class="home-insight-emoji">✨</span><span>Continua così per sbloccare insights personalizzati!</span></div>';}
function updateHomeScreen(){setGreeting();updateMainButton();updateHomeStats();updateHomeInsights();}
function toggleFabMenu(){const menu=document.getElementById('fabMenu');if(!menu)return;menu.classList.toggle('open');}
function showGardenPauseModal(){if(confirm('Vuoi mettere in pausa il giardino?\n\nLa tua pianta non appassirà per 7 giorni.\nUtile quando hai bisogno di una pausa dall\'app.')){pauseGarden(7);}}
const taskCategories={studio:['studiare','esame','lezione','compiti','tesi','scuola','università','corso','materia','storia','matematica','fisica','chimica'],lavoro:['email','meeting','report','progetto','chiamata','lavoro','riunione','presentazione','deadline','documento','cliente'],casa:['pulizie','pulire','lavare','stirare','cucinare','spesa','casa','cucina','bagno','camera','stanza','piatti','biancheria','bucato'],sociale:['uscire','amici','festa','compleanno','chiamare','sociale','cena','aperitivo','evento','appuntamento'],cura:['doccia','vestirsi','medicine','dentista','sport','palestra','correre','yoga','meditare','dormire'],admin:['bollette','banca','documenti','tasse','prenotare','email','modulo','pratica','appuntamento','telefonata']};
function detectTaskCategory(taskName){const t=taskName.toLowerCase();for(const[cat,keywords]of Object.entries(taskCategories)){if(keywords.some(k=>t.includes(k)))return cat;}return 'altro';}
function normalizeTaskName(name){return name.toLowerCase().trim().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');}
function updateTaskDatabase(taskName,category,feeling,trigger,intensity,strategyUsed,completed){if(!taskName)return;const taskId=normalizeTaskName(taskName);if(!state.tasks[taskId]){state.tasks[taskId]={name:taskName,category:category,firstSeen:new Date().toISOString(),lastMentioned:new Date().toISOString(),timesBlocked:0,timesResolved:0,feelings:{},triggers:{},strategies:{},avgIntensity:0,totalIntensity:0,count:0};}const task=state.tasks[taskId];task.lastMentioned=new Date().toISOString();task.count++;task.totalIntensity+=intensity;task.avgIntensity=(task.totalIntensity/task.count).toFixed(1);task.timesBlocked++;if(completed)task.timesResolved++;task.feelings[feeling]=(task.feelings[feeling]||0)+1;task.triggers[trigger]=(task.triggers[trigger]||0)+1;if(strategyUsed){if(!task.strategies[strategyUsed])task.strategies[strategyUsed]={used:0,completed:0};task.strategies[strategyUsed].used++;if(completed)task.strategies[strategyUsed].completed++;}saveState();}
function getBestStrategyForTask(taskId){const task=state.tasks[taskId];if(!task||!task.strategies)return null;let best=null;let bestRate=0;for(const[stratName,stats]of Object.entries(task.strategies)){if(stats.used<2)continue;const rate=stats.completed/stats.used;if(rate>bestRate){bestRate=rate;best={name:stratName,rate:rate,used:stats.used};}}return best;}

// Personal Insights & Adaptive Learning Functions
function getPersonalStrategyStats(){
  const stats={};
  state.history.forEach(h=>{
    if(h.strategyUsed){
      if(!stats[h.strategyUsed])stats[h.strategyUsed]={used:0,completed:0};
      stats[h.strategyUsed].used++;
      if(h.strategyCompleted)stats[h.strategyUsed].completed++;
    }
  });
  return Object.entries(stats)
    .filter(([,s])=>s.used>=2)
    .map(([name,s])=>({name,used:s.used,completed:s.completed,rate:s.completed/s.used}))
    .sort((a,b)=>b.rate-a.rate||b.used-a.used);
}

function getGardenEmoji(level,withered){const emojis=['🌱','🌿','🪴','🌳','🌲','🌸'];if(withered&&level>0)return'🍂';return emojis[level]||'🌱';}
function getGardenName(level){const names=['Germoglio','Piantina','Pianta giovane','Albero','Albero maestoso','Albero fiorito'];return names[level]||'Germoglio';}
function checkGardenDecay(){if(state.garden.isPaused&&state.garden.pauseUntil){if(new Date()>=new Date(state.garden.pauseUntil)){state.garden.isPaused=false;state.garden.pauseUntil=null;saveState();}}if(state.garden.isPaused)return false;if(!state.garden.lastActivityDate)return false;const now=new Date();const lastActivity=new Date(state.garden.lastActivityDate);const hoursSince=(now-lastActivity)/(1000*60*60);if(hoursSince>=72){const daysPassed=Math.floor(hoursSince/24);const levelsToLose=Math.min(2,Math.floor((daysPassed-3)/3)+1);const currentLevel=getGardenLevel(state.garden.points);if(levelsToLose>0&&currentLevel>0){const targetLevel=Math.max(0,currentLevel-levelsToLose);const levelPoints=[0,21,51,101,201,500];state.garden.points=Math.max(levelPoints[targetLevel],0);state.garden.level=targetLevel;saveState();return true;}}return hoursSince>=24;}
function addGardenPoints(points,activityName){checkGardenDecay();const wasWithered=state.garden.lastActivityDate&&(new Date()-new Date(state.garden.lastActivityDate))/(1000*60*60)>=24;const oldLevel=getGardenLevel(state.garden.points);state.garden.points+=points;state.garden.lastActivityDate=new Date().toISOString();const newLevel=getGardenLevel(state.garden.points);state.garden.level=newLevel;saveState();updateGardenBadge();let message='';if(wasWithered){message='🌱 Pianta riannaffiata! +'+points+' punti';showToast(message);setTimeout(()=>showToast('💚 Bonus recupero: +50% punti per 24h!'),1500);}else if(newLevel>oldLevel){message='🎉 LIVELLO '+newLevel+'! '+getGardenName(newLevel)+' (+'+points+' pt)';showToast(message);}else{message='✨ +'+points+' punti! '+getGardenEmoji(newLevel,false)+' '+state.garden.points+' pt';showToast(message);}}
function pauseGarden(days){state.garden.isPaused=true;const until=new Date();until.setDate(until.getDate()+days);state.garden.pauseUntil=until.toISOString();saveState();updateGardenBadge();showToast('🌙 Pianta in pausa per '+days+' giorni');}
function resumeGarden(){state.garden.isPaused=false;state.garden.pauseUntil=null;saveState();updateGardenBadge();showToast('🌱 Pausa terminata! Bentornato!');}
function updateGardenBadge(){updateMainButton();}
function updateMainButton(){const emojiEl=document.getElementById('mainGardenEmoji');const levelEl=document.getElementById('mainGardenLevel');const pointsEl=document.getElementById('mainGardenPoints');const progressEl=document.getElementById('mainGardenProgressFill');const pauseBtn=document.getElementById('gardenPauseBtn');if(!emojiEl||!levelEl||!pointsEl||!pauseBtn)return;const isWithered=checkGardenDecay();const level=getGardenLevel(state.garden.points);const emoji=getGardenEmoji(level,isWithered&&!state.garden.isPaused);const name=getGardenName(level);const points=state.garden.points;const levelPoints=[0,21,51,101,201,500];const nextLevel=Math.min(level+1,5);const pointsToNext=levelPoints[nextLevel];const prevLevelPoints=levelPoints[level];const progressInLevel=points-prevLevelPoints;const pointsNeededForLevel=pointsToNext-prevLevelPoints;const progressPercent=level>=5?100:Math.min(100,(progressInLevel/pointsNeededForLevel)*100);emojiEl.textContent=emoji;levelEl.textContent='Lv '+level+' • '+name;pointsEl.textContent=level>=5?points+' punti • Livello massimo!':points+' / '+pointsToNext+' punti al prossimo livello';if(progressEl)progressEl.style.width=progressPercent+'%';if(state.garden.isPaused){pauseBtn.textContent='▶️';pauseBtn.onclick=(e)=>{e.stopPropagation();resumeGarden();};}else{pauseBtn.textContent='⏸️';pauseBtn.onclick=(e)=>{e.stopPropagation();showGardenPauseModal();};}}
function updateHomeStats(){const streakEl=document.getElementById('statStreak');const totalEl=document.getElementById('statTotal');if(!streakEl||!totalEl)return;const streak=calculateStreak();const total=state.history.length;streakEl.textContent=streak;totalEl.textContent=total;}
function calculateStreak(){if(state.history.length===0)return 0;const sortedHistory=[...state.history].sort((a,b)=>new Date(b.date)-new Date(a.date));let streak=0;let currentDate=new Date();currentDate.setHours(0,0,0,0);for(const entry of sortedHistory){const entryDate=new Date(entry.date);entryDate.setHours(0,0,0,0);const diffDays=Math.floor((currentDate-entryDate)/(1000*60*60*24));if(diffDays===streak||diffDays===streak+1){if(diffDays===streak+1)streak++;currentDate=new Date(entryDate);}else{break;}}return streak;}
function updateHomeInsights(){const previewEl=document.getElementById('homeInsightsPreview');const listEl=document.getElementById('homeInsightsList');if(!previewEl||!listEl)return;const insights=getPersonalInsights();if(!insights||state.history.length<3){previewEl.style.display='none';return;}previewEl.style.display='block';let html='';if(insights.recentSuccess){const perc=Math.round(insights.recentSuccess.rate*100);const emoji=perc>=70?'🎉':perc>=50?'💪':'📈';html+='<div class="home-insight-item"><span class="home-insight-emoji">'+emoji+'</span><span>'+perc+'% di successo negli ultimi 7 giorni</span></div>';}if(insights.bestFeeling&&insights.bestFeeling.count>=2){html+='<div class="home-insight-item"><span class="home-insight-emoji">⭐</span><span>Per te funziona quando ti senti '+feelings.find(f=>f.id===insights.bestFeeling.feeling)?.label.toLowerCase()+'</span></div>';}if(insights.temporalPatterns&&insights.temporalPatterns.bestDay){const days=['domenica','lunedì','martedì','mercoledì','giovedì','venerdì','sabato'];html+='<div class="home-insight-item"><span class="home-insight-emoji">📅</span><span>Il tuo giorno migliore: '+days[insights.temporalPatterns.bestDay.day]+'</span></div>';}listEl.innerHTML=html||'<div class="home-insight-item"><span class="home-insight-emoji">✨</span><span>Continua così per sbloccare insights personalizzati!</span></div>';}
function updateHomeScreen(){setGreeting();updateMainButton();updateHomeStats();updateHomeInsights();}
function toggleFabMenu(){const menu=document.getElementById('fabMenu');if(!menu)return;menu.classList.toggle('open');}
function showGardenPauseModal(){if(confirm('Vuoi mettere in pausa il giardino?\n\nLa tua pianta non appassirà per 7 giorni.\nUtile quando hai bisogno di una pausa dall\'app.')){pauseGarden(7);}}
const taskCategories={studio:['studiare','esame','lezione','compiti','tesi','scuola','università','corso','materia','storia','matematica','fisica','chimica'],lavoro:['email','meeting','report','progetto','chiamata','lavoro','riunione','presentazione','deadline','documento','cliente'],casa:['pulizie','pulire','lavare','stirare','cucinare','spesa','casa','cucina','bagno','camera','stanza','piatti','biancheria','bucato'],sociale:['uscire','amici','festa','compleanno','chiamare','sociale','cena','aperitivo','evento','appuntamento'],cura:['doccia','vestirsi','medicine','dentista','sport','palestra','correre','yoga','meditare','dormire'],admin:['bollette','banca','documenti','tasse','prenotare','email','modulo','pratica','appuntamento','telefonata']};
function detectTaskCategory(taskName){const t=taskName.toLowerCase();for(const[cat,keywords]of Object.entries(taskCategories)){if(keywords.some(k=>t.includes(k)))return cat;}return 'altro';}
function normalizeTaskName(name){return name.toLowerCase().trim().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');}
function updateTaskDatabase(taskName,category,feeling,trigger,intensity,strategyUsed,completed){if(!taskName)return;const taskId=normalizeTaskName(taskName);if(!state.tasks[taskId]){state.tasks[taskId]={name:taskName,category:category,firstSeen:new Date().toISOString(),lastMentioned:new Date().toISOString(),timesBlocked:0,timesResolved:0,feelings:{},triggers:{},strategies:{},avgIntensity:0,totalIntensity:0,count:0};}const task=state.tasks[taskId];task.lastMentioned=new Date().toISOString();task.count++;task.totalIntensity+=intensity;task.avgIntensity=(task.totalIntensity/task.count).toFixed(1);task.timesBlocked++;if(completed)task.timesResolved++;task.feelings[feeling]=(task.feelings[feeling]||0)+1;task.triggers[trigger]=(task.triggers[trigger]||0)+1;if(strategyUsed){if(!task.strategies[strategyUsed])task.strategies[strategyUsed]={used:0,completed:0};task.strategies[strategyUsed].used++;if(completed)task.strategies[strategyUsed].completed++;}saveState();}
function getBestStrategyForTask(taskId){const task=state.tasks[taskId];if(!task||!task.strategies)return null;let best=null;let bestRate=0;for(const[stratName,stats]of Object.entries(task.strategies)){if(stats.used<2)continue;const rate=stats.completed/stats.used;if(rate>bestRate){bestRate=rate;best={name:stratName,rate:rate,used:stats.used};}}return best;}

// Personal Insights & Adaptive Learning Functions
function getPersonalStrategyStats(){
  const stats={};
  state.history.forEach(h=>{
    if(h.strategyUsed){
      if(!stats[h.strategyUsed])stats[h.strategyUsed]={used:0,completed:0};
      stats[h.strategyUsed].used++;
      if(h.strategyCompleted)stats[h.strategyUsed].completed++;
    }
  });
  return Object.entries(stats)
    .filter(([,s])=>s.used>=2)
    .map(([name,s])=>({name,used:s.used,completed:s.completed,rate:s.completed/s.used}))
    .sort((a,b)=>b.rate-a.rate||b.used-a.used);
}

function getGardenName(level){const names=['Germoglio','Piantina','Pianta giovane','Albero','Albero maestoso','Albero fiorito'];return names[level]||'Germoglio';}
function checkGardenDecay(){if(state.garden.isPaused&&state.garden.pauseUntil){if(new Date()>=new Date(state.garden.pauseUntil)){state.garden.isPaused=false;state.garden.pauseUntil=null;saveState();}}if(state.garden.isPaused)return false;if(!state.garden.lastActivityDate)return false;const now=new Date();const lastActivity=new Date(state.garden.lastActivityDate);const hoursSince=(now-lastActivity)/(1000*60*60);if(hoursSince>=72){const daysPassed=Math.floor(hoursSince/24);const levelsToLose=Math.min(2,Math.floor((daysPassed-3)/3)+1);const currentLevel=getGardenLevel(state.garden.points);if(levelsToLose>0&&currentLevel>0){const targetLevel=Math.max(0,currentLevel-levelsToLose);const levelPoints=[0,21,51,101,201,500];state.garden.points=Math.max(levelPoints[targetLevel],0);state.garden.level=targetLevel;saveState();return true;}}return hoursSince>=24;}
function addGardenPoints(points,activityName){checkGardenDecay();const wasWithered=state.garden.lastActivityDate&&(new Date()-new Date(state.garden.lastActivityDate))/(1000*60*60)>=24;const oldLevel=getGardenLevel(state.garden.points);state.garden.points+=points;state.garden.lastActivityDate=new Date().toISOString();const newLevel=getGardenLevel(state.garden.points);state.garden.level=newLevel;saveState();updateGardenBadge();let message='';if(wasWithered){message='🌱 Pianta riannaffiata! +'+points+' punti';showToast(message);setTimeout(()=>showToast('💚 Bonus recupero: +50% punti per 24h!'),1500);}else if(newLevel>oldLevel){message='🎉 LIVELLO '+newLevel+'! '+getGardenName(newLevel)+' (+'+points+' pt)';showToast(message);}else{message='✨ +'+points+' punti! '+getGardenEmoji(newLevel,false)+' '+state.garden.points+' pt';showToast(message);}}
function pauseGarden(days){state.garden.isPaused=true;const until=new Date();until.setDate(until.getDate()+days);state.garden.pauseUntil=until.toISOString();saveState();updateGardenBadge();showToast('🌙 Pianta in pausa per '+days+' giorni');}
function resumeGarden(){state.garden.isPaused=false;state.garden.pauseUntil=null;saveState();updateGardenBadge();showToast('🌱 Pausa terminata! Bentornato!');}
function updateGardenBadge(){updateMainButton();}
function updateMainButton(){const emojiEl=document.getElementById('mainGardenEmoji');const levelEl=document.getElementById('mainGardenLevel');const pointsEl=document.getElementById('mainGardenPoints');const progressEl=document.getElementById('mainGardenProgressFill');const pauseBtn=document.getElementById('gardenPauseBtn');if(!emojiEl||!levelEl||!pointsEl||!pauseBtn)return;const isWithered=checkGardenDecay();const level=getGardenLevel(state.garden.points);const emoji=getGardenEmoji(level,isWithered&&!state.garden.isPaused);const name=getGardenName(level);const points=state.garden.points;const levelPoints=[0,21,51,101,201,500];const nextLevel=Math.min(level+1,5);const pointsToNext=levelPoints[nextLevel];const prevLevelPoints=levelPoints[level];const progressInLevel=points-prevLevelPoints;const pointsNeededForLevel=pointsToNext-prevLevelPoints;const progressPercent=level>=5?100:Math.min(100,(progressInLevel/pointsNeededForLevel)*100);emojiEl.textContent=emoji;levelEl.textContent='Lv '+level+' • '+name;pointsEl.textContent=level>=5?points+' punti • Livello massimo!':points+' / '+pointsToNext+' punti al prossimo livello';if(progressEl)progressEl.style.width=progressPercent+'%';if(state.garden.isPaused){pauseBtn.textContent='▶️';pauseBtn.onclick=(e)=>{e.stopPropagation();resumeGarden();};}else{pauseBtn.textContent='⏸️';pauseBtn.onclick=(e)=>{e.stopPropagation();showGardenPauseModal();};}}
function updateHomeStats(){const streakEl=document.getElementById('statStreak');const totalEl=document.getElementById('statTotal');if(!streakEl||!totalEl)return;const streak=calculateStreak();const total=state.history.length;streakEl.textContent=streak;totalEl.textContent=total;}
function calculateStreak(){if(state.history.length===0)return 0;const sortedHistory=[...state.history].sort((a,b)=>new Date(b.date)-new Date(a.date));let streak=0;let currentDate=new Date();currentDate.setHours(0,0,0,0);for(const entry of sortedHistory){const entryDate=new Date(entry.date);entryDate.setHours(0,0,0,0);const diffDays=Math.floor((currentDate-entryDate)/(1000*60*60*24));if(diffDays===streak||diffDays===streak+1){if(diffDays===streak+1)streak++;currentDate=new Date(entryDate);}else{break;}}return streak;}
function updateHomeInsights(){const previewEl=document.getElementById('homeInsightsPreview');const listEl=document.getElementById('homeInsightsList');if(!previewEl||!listEl)return;const insights=getPersonalInsights();if(!insights||state.history.length<3){previewEl.style.display='none';return;}previewEl.style.display='block';let html='';if(insights.recentSuccess){const perc=Math.round(insights.recentSuccess.rate*100);const emoji=perc>=70?'🎉':perc>=50?'💪':'📈';html+='<div class="home-insight-item"><span class="home-insight-emoji">'+emoji+'</span><span>'+perc+'% di successo negli ultimi 7 giorni</span></div>';}if(insights.bestFeeling&&insights.bestFeeling.count>=2){html+='<div class="home-insight-item"><span class="home-insight-emoji">⭐</span><span>Per te funziona quando ti senti '+feelings.find(f=>f.id===insights.bestFeeling.feeling)?.label.toLowerCase()+'</span></div>';}if(insights.temporalPatterns&&insights.temporalPatterns.bestDay){const days=['domenica','lunedì','martedì','mercoledì','giovedì','venerdì','sabato'];html+='<div class="home-insight-item"><span class="home-insight-emoji">📅</span><span>Il tuo giorno migliore: '+days[insights.temporalPatterns.bestDay.day]+'</span></div>';}listEl.innerHTML=html||'<div class="home-insight-item"><span class="home-insight-emoji">✨</span><span>Continua così per sbloccare insights personalizzati!</span></div>';}
function updateHomeScreen(){setGreeting();updateMainButton();updateHomeStats();updateHomeInsights();}
function toggleFabMenu(){const menu=document.getElementById('fabMenu');if(!menu)return;menu.classList.toggle('open');}
function showGardenPauseModal(){if(confirm('Vuoi mettere in pausa il giardino?\n\nLa tua pianta non appassirà per 7 giorni.\nUtile quando hai bisogno di una pausa dall\'app.')){pauseGarden(7);}}
const taskCategories={studio:['studiare','esame','lezione','compiti','tesi','scuola','università','corso','materia','storia','matematica','fisica','chimica'],lavoro:['email','meeting','report','progetto','chiamata','lavoro','riunione','presentazione','deadline','documento','cliente'],casa:['pulizie','pulire','lavare','stirare','cucinare','spesa','casa','cucina','bagno','camera','stanza','piatti','biancheria','bucato'],sociale:['uscire','amici','festa','compleanno','chiamare','sociale','cena','aperitivo','evento','appuntamento'],cura:['doccia','vestirsi','medicine','dentista','sport','palestra','correre','yoga','meditare','dormire'],admin:['bollette','banca','documenti','tasse','prenotare','email','modulo','pratica','appuntamento','telefonata']};
function detectTaskCategory(taskName){const t=taskName.toLowerCase();for(const[cat,keywords]of Object.entries(taskCategories)){if(keywords.some(k=>t.includes(k)))return cat;}return 'altro';}
function normalizeTaskName(name){return name.toLowerCase().trim().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');}
function updateTaskDatabase(taskName,category,feeling,trigger,intensity,strategyUsed,completed){if(!taskName)return;const taskId=normalizeTaskName(taskName);if(!state.tasks[taskId]){state.tasks[taskId]={name:taskName,category:category,firstSeen:new Date().toISOString(),lastMentioned:new Date().toISOString(),timesBlocked:0,timesResolved:0,feelings:{},triggers:{},strategies:{},avgIntensity:0,totalIntensity:0,count:0};}const task=state.tasks[taskId];task.lastMentioned=new Date().toISOString();task.count++;task.totalIntensity+=intensity;task.avgIntensity=(task.totalIntensity/task.count).toFixed(1);task.timesBlocked++;if(completed)task.timesResolved++;task.feelings[feeling]=(task.feelings[feeling]||0)+1;task.triggers[trigger]=(task.triggers[trigger]||0)+1;if(strategyUsed){if(!task.strategies[strategyUsed])task.strategies[strategyUsed]={used:0,completed:0};task.strategies[strategyUsed].used++;if(completed)task.strategies[strategyUsed].completed++;}saveState();}
function getBestStrategyForTask(taskId){const task=state.tasks[taskId];if(!task||!task.strategies)return null;let best=null;let bestRate=0;for(const[stratName,stats]of Object.entries(task.strategies)){if(stats.used<2)continue;const rate=stats.completed/stats.used;if(rate>bestRate){bestRate=rate;best={name:stratName,rate:rate,used:stats.used};}}return best;}

// Personal Insights & Adaptive Learning Functions
function getPersonalStrategyStats(){
  const stats={};
  state.history.forEach(h=>{
    if(h.strategyUsed){
      if(!stats[h.strategyUsed])stats[h.strategyUsed]={used:0,completed:0};
      stats[h.strategyUsed].used++;
      if(h.strategyCompleted)stats[h.strategyUsed].completed++;
    }
  });
  return Object.entries(stats)
    .filter(([,s])=>s.used>=2)
    .map(([name,s])=>({name,used:s.used,completed:s.completed,rate:s.completed/s.used}))
    .sort((a,b)=>b.rate-a.rate||b.used-a.used);
}

function addGardenPoints(points,activityName){checkGardenDecay();const wasWithered=state.garden.lastActivityDate&&(new Date()-new Date(state.garden.lastActivityDate))/(1000*60*60)>=24;const oldLevel=getGardenLevel(state.garden.points);state.garden.points+=points;state.garden.lastActivityDate=new Date().toISOString();const newLevel=getGardenLevel(state.garden.points);state.garden.level=newLevel;saveState();updateGardenBadge();let message='';if(wasWithered){message='🌱 Pianta riannaffiata! +'+points+' punti';showToast(message);setTimeout(()=>showToast('💚 Bonus recupero: +50% punti per 24h!'),1500);}else if(newLevel>oldLevel){message='🎉 LIVELLO '+newLevel+'! '+getGardenName(newLevel)+' (+'+points+' pt)';showToast(message);}else{message='✨ +'+points+' punti! '+getGardenEmoji(newLevel,false)+' '+state.garden.points+' pt';showToast(message);}}
function pauseGarden(days){state.garden.isPaused=true;const until=new Date();until.setDate(until.getDate()+days);state.garden.pauseUntil=until.toISOString();saveState();updateGardenBadge();showToast('🌙 Pianta in pausa per '+days+' giorni');}
function resumeGarden(){state.garden.isPaused=false;state.garden.pauseUntil=null;saveState();updateGardenBadge();showToast('🌱 Pausa terminata! Bentornato!');}
function updateGardenBadge(){updateMainButton();}
function updateMainButton(){const emojiEl=document.getElementById('mainGardenEmoji');const levelEl=document.getElementById('mainGardenLevel');const pointsEl=document.getElementById('mainGardenPoints');const progressEl=document.getElementById('mainGardenProgressFill');const pauseBtn=document.getElementById('gardenPauseBtn');if(!emojiEl||!levelEl||!pointsEl||!pauseBtn)return;const isWithered=checkGardenDecay();const level=getGardenLevel(state.garden.points);const emoji=getGardenEmoji(level,isWithered&&!state.garden.isPaused);const name=getGardenName(level);const points=state.garden.points;const levelPoints=[0,21,51,101,201,500];const nextLevel=Math.min(level+1,5);const pointsToNext=levelPoints[nextLevel];const prevLevelPoints=levelPoints[level];const progressInLevel=points-prevLevelPoints;const pointsNeededForLevel=pointsToNext-prevLevelPoints;const progressPercent=level>=5?100:Math.min(100,(progressInLevel/pointsNeededForLevel)*100);emojiEl.textContent=emoji;levelEl.textContent='Lv '+level+' • '+name;pointsEl.textContent=level>=5?points+' punti • Livello massimo!':points+' / '+pointsToNext+' punti al prossimo livello';if(progressEl)progressEl.style.width=progressPercent+'%';if(state.garden.isPaused){pauseBtn.textContent='▶️';pauseBtn.onclick=(e)=>{e.stopPropagation();resumeGarden();};}else{pauseBtn.textContent='⏸️';pauseBtn.onclick=(e)=>{e.stopPropagation();showGardenPauseModal();};}}
function updateHomeStats(){const streakEl=document.getElementById('statStreak');const totalEl=document.getElementById('statTotal');if(!streakEl||!totalEl)return;const streak=calculateStreak();const total=state.history.length;streakEl.textContent=streak;totalEl.textContent=total;}
function calculateStreak(){if(state.history.length===0)return 0;const sortedHistory=[...state.history].sort((a,b)=>new Date(b.date)-new Date(a.date));let streak=0;let currentDate=new Date();currentDate.setHours(0,0,0,0);for(const entry of sortedHistory){const entryDate=new Date(entry.date);entryDate.setHours(0,0,0,0);const diffDays=Math.floor((currentDate-entryDate)/(1000*60*60*24));if(diffDays===streak||diffDays===streak+1){if(diffDays===streak+1)streak++;currentDate=new Date(entryDate);}else{break;}}return streak;}
function updateHomeInsights(){const previewEl=document.getElementById('homeInsightsPreview');const listEl=document.getElementById('homeInsightsList');if(!previewEl||!listEl)return;const insights=getPersonalInsights();if(!insights||state.history.length<3){previewEl.style.display='none';return;}previewEl.style.display='block';let html='';if(insights.recentSuccess){const perc=Math.round(insights.recentSuccess.rate*100);const emoji=perc>=70?'🎉':perc>=50?'💪':'📈';html+='<div class="home-insight-item"><span class="home-insight-emoji">'+emoji+'</span><span>'+perc+'% di successo negli ultimi 7 giorni</span></div>';}if(insights.bestFeeling&&insights.bestFeeling.count>=2){html+='<div class="home-insight-item"><span class="home-insight-emoji">⭐</span><span>Per te funziona quando ti senti '+feelings.find(f=>f.id===insights.bestFeeling.feeling)?.label.toLowerCase()+'</span></div>';}if(insights.temporalPatterns&&insights.temporalPatterns.bestDay){const days=['domenica','lunedì','martedì','mercoledì','giovedì','venerdì','sabato'];html+='<div class="home-insight-item"><span class="home-insight-emoji">📅</span><span>Il tuo giorno migliore: '+days[insights.temporalPatterns.bestDay.day]+'</span></div>';}listEl.innerHTML=html||'<div class="home-insight-item"><span class="home-insight-emoji">✨</span><span>Continua così per sbloccare insights personalizzati!</span></div>';}
function updateHomeScreen(){setGreeting();updateMainButton();updateHomeStats();updateHomeInsights();}
function toggleFabMenu(){const menu=document.getElementById('fabMenu');if(!menu)return;menu.classList.toggle('open');}
function showGardenPauseModal(){if(confirm('Vuoi mettere in pausa il giardino?\n\nLa tua pianta non appassirà per 7 giorni.\nUtile quando hai bisogno di una pausa dall\'app.')){pauseGarden(7);}}
const taskCategories={studio:['studiare','esame','lezione','compiti','tesi','scuola','università','corso','materia','storia','matematica','fisica','chimica'],lavoro:['email','meeting','report','progetto','chiamata','lavoro','riunione','presentazione','deadline','documento','cliente'],casa:['pulizie','pulire','lavare','stirare','cucinare','spesa','casa','cucina','bagno','camera','stanza','piatti','biancheria','bucato'],sociale:['uscire','amici','festa','compleanno','chiamare','sociale','cena','aperitivo','evento','appuntamento'],cura:['doccia','vestirsi','medicine','dentista','sport','palestra','correre','yoga','meditare','dormire'],admin:['bollette','banca','documenti','tasse','prenotare','email','modulo','pratica','appuntamento','telefonata']};
function detectTaskCategory(taskName){const t=taskName.toLowerCase();for(const[cat,keywords]of Object.entries(taskCategories)){if(keywords.some(k=>t.includes(k)))return cat;}return 'altro';}
function normalizeTaskName(name){return name.toLowerCase().trim().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');}
function updateTaskDatabase(taskName,category,feeling,trigger,intensity,strategyUsed,completed){if(!taskName)return;const taskId=normalizeTaskName(taskName);if(!state.tasks[taskId]){state.tasks[taskId]={name:taskName,category:category,firstSeen:new Date().toISOString(),lastMentioned:new Date().toISOString(),timesBlocked:0,timesResolved:0,feelings:{},triggers:{},strategies:{},avgIntensity:0,totalIntensity:0,count:0};}const task=state.tasks[taskId];task.lastMentioned=new Date().toISOString();task.count++;task.totalIntensity+=intensity;task.avgIntensity=(task.totalIntensity/task.count).toFixed(1);task.timesBlocked++;if(completed)task.timesResolved++;task.feelings[feeling]=(task.feelings[feeling]||0)+1;task.triggers[trigger]=(task.triggers[trigger]||0)+1;if(strategyUsed){if(!task.strategies[strategyUsed])task.strategies[strategyUsed]={used:0,completed:0};task.strategies[strategyUsed].used++;if(completed)task.strategies[strategyUsed].completed++;}saveState();}
function getBestStrategyForTask(taskId){const task=state.tasks[taskId];if(!task||!task.strategies)return null;let best=null;let bestRate=0;for(const[stratName,stats]of Object.entries(task.strategies)){if(stats.used<2)continue;const rate=stats.completed/stats.used;if(rate>bestRate){bestRate=rate;best={name:stratName,rate:rate,used:stats.used};}}return best;}

// Personal Insights & Adaptive Learning Functions
function getPersonalStrategyStats(){
  const stats={};
  state.history.forEach(h=>{
    if(h.strategyUsed){
      if(!stats[h.strategyUsed])stats[h.strategyUsed]={used:0,completed:0};
      stats[h.strategyUsed].used++;
      if(h.strategyCompleted)stats[h.strategyUsed].completed++;
    }
  });
  return Object.entries(stats)
    .filter(([,s])=>s.used>=2)
    .map(([name,s])=>({name,used:s.used,completed:s.completed,rate:s.completed/s.used}))
    .sort((a,b)=>b.rate-a.rate||b.used-a.used);
}

function pauseGarden(days){state.garden.isPaused=true;const until=new Date();until.setDate(until.getDate()+days);state.garden.pauseUntil=until.toISOString();saveState();updateGardenBadge();showToast('🌙 Pianta in pausa per '+days+' giorni');}
function resumeGarden(){state.garden.isPaused=false;state.garden.pauseUntil=null;saveState();updateGardenBadge();showToast('🌱 Pausa terminata! Bentornato!');}
function updateGardenBadge(){updateMainButton();}
function updateMainButton(){const emojiEl=document.getElementById('mainGardenEmoji');const levelEl=document.getElementById('mainGardenLevel');const pointsEl=document.getElementById('mainGardenPoints');const progressEl=document.getElementById('mainGardenProgressFill');const pauseBtn=document.getElementById('gardenPauseBtn');if(!emojiEl||!levelEl||!pointsEl||!pauseBtn)return;const isWithered=checkGardenDecay();const level=getGardenLevel(state.garden.points);const emoji=getGardenEmoji(level,isWithered&&!state.garden.isPaused);const name=getGardenName(level);const points=state.garden.points;const levelPoints=[0,21,51,101,201,500];const nextLevel=Math.min(level+1,5);const pointsToNext=levelPoints[nextLevel];const prevLevelPoints=levelPoints[level];const progressInLevel=points-prevLevelPoints;const pointsNeededForLevel=pointsToNext-prevLevelPoints;const progressPercent=level>=5?100:Math.min(100,(progressInLevel/pointsNeededForLevel)*100);emojiEl.textContent=emoji;levelEl.textContent='Lv '+level+' • '+name;pointsEl.textContent=level>=5?points+' punti • Livello massimo!':points+' / '+pointsToNext+' punti al prossimo livello';if(progressEl)progressEl.style.width=progressPercent+'%';if(state.garden.isPaused){pauseBtn.textContent='▶️';pauseBtn.onclick=(e)=>{e.stopPropagation();resumeGarden();};}else{pauseBtn.textContent='⏸️';pauseBtn.onclick=(e)=>{e.stopPropagation();showGardenPauseModal();};}}
function updateHomeStats(){const streakEl=document.getElementById('statStreak');const totalEl=document.getElementById('statTotal');if(!streakEl||!totalEl)return;const streak=calculateStreak();const total=state.history.length;streakEl.textContent=streak;totalEl.textContent=total;}
function calculateStreak(){if(state.history.length===0)return 0;const sortedHistory=[...state.history].sort((a,b)=>new Date(b.date)-new Date(a.date));let streak=0;let currentDate=new Date();currentDate.setHours(0,0,0,0);for(const entry of sortedHistory){const entryDate=new Date(entry.date);entryDate.setHours(0,0,0,0);const diffDays=Math.floor((currentDate-entryDate)/(1000*60*60*24));if(diffDays===streak||diffDays===streak+1){if(diffDays===streak+1)streak++;currentDate=new Date(entryDate);}else{break;}}return streak;}
function updateHomeInsights(){const previewEl=document.getElementById('homeInsightsPreview');const listEl=document.getElementById('homeInsightsList');if(!previewEl||!listEl)return;const insights=getPersonalInsights();if(!insights||state.history.length<3){previewEl.style.display='none';return;}previewEl.style.display='block';let html='';if(insights.recentSuccess){const perc=Math.round(insights.recentSuccess.rate*100);const emoji=perc>=70?'🎉':perc>=50?'💪':'📈';html+='<div class="home-insight-item"><span class="home-insight-emoji">'+emoji+'</span><span>'+perc+'% di successo negli ultimi 7 giorni</span></div>';}if(insights.bestFeeling&&insights.bestFeeling.count>=2){html+='<div class="home-insight-item"><span class="home-insight-emoji">⭐</span><span>Per te funziona quando ti senti '+feelings.find(f=>f.id===insights.bestFeeling.feeling)?.label.toLowerCase()+'</span></div>';}if(insights.temporalPatterns&&insights.temporalPatterns.bestDay){const days=['domenica','lunedì','martedì','mercoledì','giovedì','venerdì','sabato'];html+='<div class="home-insight-item"><span class="home-insight-emoji">📅</span><span>Il tuo giorno migliore: '+days[insights.temporalPatterns.bestDay.day]+'</span></div>';}listEl.innerHTML=html||'<div class="home-insight-item"><span class="home-insight-emoji">✨</span><span>Continua così per sbloccare insights personalizzati!</span></div>';}
function updateHomeScreen(){setGreeting();updateMainButton();updateHomeStats();updateHomeInsights();}
function toggleFabMenu(){const menu=document.getElementById('fabMenu');if(!menu)return;menu.classList.toggle('open');}
function showGardenPauseModal(){if(confirm('Vuoi mettere in pausa il giardino?\n\nLa tua pianta non appassirà per 7 giorni.\nUtile quando hai bisogno di una pausa dall\'app.')){pauseGarden(7);}}
const taskCategories={studio:['studiare','esame','lezione','compiti','tesi','scuola','università','corso','materia','storia','matematica','fisica','chimica'],lavoro:['email','meeting','report','progetto','chiamata','lavoro','riunione','presentazione','deadline','documento','cliente'],casa:['pulizie','pulire','lavare','stirare','cucinare','spesa','casa','cucina','bagno','camera','stanza','piatti','biancheria','bucato'],sociale:['uscire','amici','festa','compleanno','chiamare','sociale','cena','aperitivo','evento','appuntamento'],cura:['doccia','vestirsi','medicine','dentista','sport','palestra','correre','yoga','meditare','dormire'],admin:['bollette','banca','documenti','tasse','prenotare','email','modulo','pratica','appuntamento','telefonata']};
function detectTaskCategory(taskName){const t=taskName.toLowerCase();for(const[cat,keywords]of Object.entries(taskCategories)){if(keywords.some(k=>t.includes(k)))return cat;}return 'altro';}
function normalizeTaskName(name){return name.toLowerCase().trim().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');}
function updateTaskDatabase(taskName,category,feeling,trigger,intensity,strategyUsed,completed){if(!taskName)return;const taskId=normalizeTaskName(taskName);if(!state.tasks[taskId]){state.tasks[taskId]={name:taskName,category:category,firstSeen:new Date().toISOString(),lastMentioned:new Date().toISOString(),timesBlocked:0,timesResolved:0,feelings:{},triggers:{},strategies:{},avgIntensity:0,totalIntensity:0,count:0};}const task=state.tasks[taskId];task.lastMentioned=new Date().toISOString();task.count++;task.totalIntensity+=intensity;task.avgIntensity=(task.totalIntensity/task.count).toFixed(1);task.timesBlocked++;if(completed)task.timesResolved++;task.feelings[feeling]=(task.feelings[feeling]||0)+1;task.triggers[trigger]=(task.triggers[trigger]||0)+1;if(strategyUsed){if(!task.strategies[strategyUsed])task.strategies[strategyUsed]={used:0,completed:0};task.strategies[strategyUsed].used++;if(completed)task.strategies[strategyUsed].completed++;}saveState();}
function getBestStrategyForTask(taskId){const task=state.tasks[taskId];if(!task||!task.strategies)return null;let best=null;let bestRate=0;for(const[stratName,stats]of Object.entries(task.strategies)){if(stats.used<2)continue;const rate=stats.completed/stats.used;if(rate>bestRate){bestRate=rate;best={name:stratName,rate:rate,used:stats.used};}}return best;}

// Personal Insights & Adaptive Learning Functions
function getPersonalStrategyStats(){
  const stats={};
  state.history.forEach(h=>{
    if(h.strategyUsed){
      if(!stats[h.strategyUsed])stats[h.strategyUsed]={used:0,completed:0};
      stats[h.strategyUsed].used++;
      if(h.strategyCompleted)stats[h.strategyUsed].completed++;
    }
  });
  return Object.entries(stats)
    .filter(([,s])=>s.used>=2)
    .map(([name,s])=>({name,used:s.used,completed:s.completed,rate:s.completed/s.used}))
    .sort((a,b)=>b.rate-a.rate||b.used-a.used);
}

function resumeGarden(){state.garden.isPaused=false;state.garden.pauseUntil=null;saveState();updateGardenBadge();showToast('🌱 Pausa terminata! Bentornato!');}
function updateGardenBadge(){updateMainButton();}
function updateMainButton(){const emojiEl=document.getElementById('mainGardenEmoji');const levelEl=document.getElementById('mainGardenLevel');const pointsEl=document.getElementById('mainGardenPoints');const progressEl=document.getElementById('mainGardenProgressFill');const pauseBtn=document.getElementById('gardenPauseBtn');if(!emojiEl||!levelEl||!pointsEl||!pauseBtn)return;const isWithered=checkGardenDecay();const level=getGardenLevel(state.garden.points);const emoji=getGardenEmoji(level,isWithered&&!state.garden.isPaused);const name=getGardenName(level);const points=state.garden.points;const levelPoints=[0,21,51,101,201,500];const nextLevel=Math.min(level+1,5);const pointsToNext=levelPoints[nextLevel];const prevLevelPoints=levelPoints[level];const progressInLevel=points-prevLevelPoints;const pointsNeededForLevel=pointsToNext-prevLevelPoints;const progressPercent=level>=5?100:Math.min(100,(progressInLevel/pointsNeededForLevel)*100);emojiEl.textContent=emoji;levelEl.textContent='Lv '+level+' • '+name;pointsEl.textContent=level>=5?points+' punti • Livello massimo!':points+' / '+pointsToNext+' punti al prossimo livello';if(progressEl)progressEl.style.width=progressPercent+'%';if(state.garden.isPaused){pauseBtn.textContent='▶️';pauseBtn.onclick=(e)=>{e.stopPropagation();resumeGarden();};}else{pauseBtn.textContent='⏸️';pauseBtn.onclick=(e)=>{e.stopPropagation();showGardenPauseModal();};}}
function updateHomeStats(){const streakEl=document.getElementById('statStreak');const totalEl=document.getElementById('statTotal');if(!streakEl||!totalEl)return;const streak=calculateStreak();const total=state.history.length;streakEl.textContent=streak;totalEl.textContent=total;}
function calculateStreak(){if(state.history.length===0)return 0;const sortedHistory=[...state.history].sort((a,b)=>new Date(b.date)-new Date(a.date));let streak=0;let currentDate=new Date();currentDate.setHours(0,0,0,0);for(const entry of sortedHistory){const entryDate=new Date(entry.date);entryDate.setHours(0,0,0,0);const diffDays=Math.floor((currentDate-entryDate)/(1000*60*60*24));if(diffDays===streak||diffDays===streak+1){if(diffDays===streak+1)streak++;currentDate=new Date(entryDate);}else{break;}}return streak;}
function updateHomeInsights(){const previewEl=document.getElementById('homeInsightsPreview');const listEl=document.getElementById('homeInsightsList');if(!previewEl||!listEl)return;const insights=getPersonalInsights();if(!insights||state.history.length<3){previewEl.style.display='none';return;}previewEl.style.display='block';let html='';if(insights.recentSuccess){const perc=Math.round(insights.recentSuccess.rate*100);const emoji=perc>=70?'🎉':perc>=50?'💪':'📈';html+='<div class="home-insight-item"><span class="home-insight-emoji">'+emoji+'</span><span>'+perc+'% di successo negli ultimi 7 giorni</span></div>';}if(insights.bestFeeling&&insights.bestFeeling.count>=2){html+='<div class="home-insight-item"><span class="home-insight-emoji">⭐</span><span>Per te funziona quando ti senti '+feelings.find(f=>f.id===insights.bestFeeling.feeling)?.label.toLowerCase()+'</span></div>';}if(insights.temporalPatterns&&insights.temporalPatterns.bestDay){const days=['domenica','lunedì','martedì','mercoledì','giovedì','venerdì','sabato'];html+='<div class="home-insight-item"><span class="home-insight-emoji">📅</span><span>Il tuo giorno migliore: '+days[insights.temporalPatterns.bestDay.day]+'</span></div>';}listEl.innerHTML=html||'<div class="home-insight-item"><span class="home-insight-emoji">✨</span><span>Continua così per sbloccare insights personalizzati!</span></div>';}
function updateHomeScreen(){setGreeting();updateMainButton();updateHomeStats();updateHomeInsights();}
function toggleFabMenu(){const menu=document.getElementById('fabMenu');if(!menu)return;menu.classList.toggle('open');}
function showGardenPauseModal(){if(confirm('Vuoi mettere in pausa il giardino?\n\nLa tua pianta non appassirà per 7 giorni.\nUtile quando hai bisogno di una pausa dall\'app.')){pauseGarden(7);}}
const taskCategories={studio:['studiare','esame','lezione','compiti','tesi','scuola','università','corso','materia','storia','matematica','fisica','chimica'],lavoro:['email','meeting','report','progetto','chiamata','lavoro','riunione','presentazione','deadline','documento','cliente'],casa:['pulizie','pulire','lavare','stirare','cucinare','spesa','casa','cucina','bagno','camera','stanza','piatti','biancheria','bucato'],sociale:['uscire','amici','festa','compleanno','chiamare','sociale','cena','aperitivo','evento','appuntamento'],cura:['doccia','vestirsi','medicine','dentista','sport','palestra','correre','yoga','meditare','dormire'],admin:['bollette','banca','documenti','tasse','prenotare','email','modulo','pratica','appuntamento','telefonata']};
function detectTaskCategory(taskName){const t=taskName.toLowerCase();for(const[cat,keywords]of Object.entries(taskCategories)){if(keywords.some(k=>t.includes(k)))return cat;}return 'altro';}
function normalizeTaskName(name){return name.toLowerCase().trim().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');}
function updateTaskDatabase(taskName,category,feeling,trigger,intensity,strategyUsed,completed){if(!taskName)return;const taskId=normalizeTaskName(taskName);if(!state.tasks[taskId]){state.tasks[taskId]={name:taskName,category:category,firstSeen:new Date().toISOString(),lastMentioned:new Date().toISOString(),timesBlocked:0,timesResolved:0,feelings:{},triggers:{},strategies:{},avgIntensity:0,totalIntensity:0,count:0};}const task=state.tasks[taskId];task.lastMentioned=new Date().toISOString();task.count++;task.totalIntensity+=intensity;task.avgIntensity=(task.totalIntensity/task.count).toFixed(1);task.timesBlocked++;if(completed)task.timesResolved++;task.feelings[feeling]=(task.feelings[feeling]||0)+1;task.triggers[trigger]=(task.triggers[trigger]||0)+1;if(strategyUsed){if(!task.strategies[strategyUsed])task.strategies[strategyUsed]={used:0,completed:0};task.strategies[strategyUsed].used++;if(completed)task.strategies[strategyUsed].completed++;}saveState();}
function getBestStrategyForTask(taskId){const task=state.tasks[taskId];if(!task||!task.strategies)return null;let best=null;let bestRate=0;for(const[stratName,stats]of Object.entries(task.strategies)){if(stats.used<2)continue;const rate=stats.completed/stats.used;if(rate>bestRate){bestRate=rate;best={name:stratName,rate:rate,used:stats.used};}}return best;}

// Personal Insights & Adaptive Learning Functions
function getPersonalStrategyStats(){
  const stats={};
  state.history.forEach(h=>{
    if(h.strategyUsed){
      if(!stats[h.strategyUsed])stats[h.strategyUsed]={used:0,completed:0};
      stats[h.strategyUsed].used++;
      if(h.strategyCompleted)stats[h.strategyUsed].completed++;
    }
  });
  return Object.entries(stats)
    .filter(([,s])=>s.used>=2)
    .map(([name,s])=>({name,used:s.used,completed:s.completed,rate:s.completed/s.used}))
    .sort((a,b)=>b.rate-a.rate||b.used-a.used);
}

function updateGardenBadge(){updateMainButton();}
function updateMainButton(){const emojiEl=document.getElementById('mainGardenEmoji');const levelEl=document.getElementById('mainGardenLevel');const pointsEl=document.getElementById('mainGardenPoints');const progressEl=document.getElementById('mainGardenProgressFill');const pauseBtn=document.getElementById('gardenPauseBtn');if(!emojiEl||!levelEl||!pointsEl||!pauseBtn)return;const isWithered=checkGardenDecay();const level=getGardenLevel(state.garden.points);const emoji=getGardenEmoji(level,isWithered&&!state.garden.isPaused);const name=getGardenName(level);const points=state.garden.points;const levelPoints=[0,21,51,101,201,500];const nextLevel=Math.min(level+1,5);const pointsToNext=levelPoints[nextLevel];const prevLevelPoints=levelPoints[level];const progressInLevel=points-prevLevelPoints;const pointsNeededForLevel=pointsToNext-prevLevelPoints;const progressPercent=level>=5?100:Math.min(100,(progressInLevel/pointsNeededForLevel)*100);emojiEl.textContent=emoji;levelEl.textContent='Lv '+level+' • '+name;pointsEl.textContent=level>=5?points+' punti • Livello massimo!':points+' / '+pointsToNext+' punti al prossimo livello';if(progressEl)progressEl.style.width=progressPercent+'%';if(state.garden.isPaused){pauseBtn.textContent='▶️';pauseBtn.onclick=(e)=>{e.stopPropagation();resumeGarden();};}else{pauseBtn.textContent='⏸️';pauseBtn.onclick=(e)=>{e.stopPropagation();showGardenPauseModal();};}}
function updateHomeStats(){const streakEl=document.getElementById('statStreak');const totalEl=document.getElementById('statTotal');if(!streakEl||!totalEl)return;const streak=calculateStreak();const total=state.history.length;streakEl.textContent=streak;totalEl.textContent=total;}
function calculateStreak(){if(state.history.length===0)return 0;const sortedHistory=[...state.history].sort((a,b)=>new Date(b.date)-new Date(a.date));let streak=0;let currentDate=new Date();currentDate.setHours(0,0,0,0);for(const entry of sortedHistory){const entryDate=new Date(entry.date);entryDate.setHours(0,0,0,0);const diffDays=Math.floor((currentDate-entryDate)/(1000*60*60*24));if(diffDays===streak||diffDays===streak+1){if(diffDays===streak+1)streak++;currentDate=new Date(entryDate);}else{break;}}return streak;}
function updateHomeInsights(){const previewEl=document.getElementById('homeInsightsPreview');const listEl=document.getElementById('homeInsightsList');if(!previewEl||!listEl)return;const insights=getPersonalInsights();if(!insights||state.history.length<3){previewEl.style.display='none';return;}previewEl.style.display='block';let html='';if(insights.recentSuccess){const perc=Math.round(insights.recentSuccess.rate*100);const emoji=perc>=70?'🎉':perc>=50?'💪':'📈';html+='<div class="home-insight-item"><span class="home-insight-emoji">'+emoji+'</span><span>'+perc+'% di successo negli ultimi 7 giorni</span></div>';}if(insights.bestFeeling&&insights.bestFeeling.count>=2){html+='<div class="home-insight-item"><span class="home-insight-emoji">⭐</span><span>Per te funziona quando ti senti '+feelings.find(f=>f.id===insights.bestFeeling.feeling)?.label.toLowerCase()+'</span></div>';}if(insights.temporalPatterns&&insights.temporalPatterns.bestDay){const days=['domenica','lunedì','martedì','mercoledì','giovedì','venerdì','sabato'];html+='<div class="home-insight-item"><span class="home-insight-emoji">📅</span><span>Il tuo giorno migliore: '+days[insights.temporalPatterns.bestDay.day]+'</span></div>';}listEl.innerHTML=html||'<div class="home-insight-item"><span class="home-insight-emoji">✨</span><span>Continua così per sbloccare insights personalizzati!</span></div>';}
function updateHomeScreen(){setGreeting();updateMainButton();updateHomeStats();updateHomeInsights();}
function toggleFabMenu(){const menu=document.getElementById('fabMenu');if(!menu)return;menu.classList.toggle('open');}
function showGardenPauseModal(){if(confirm('Vuoi mettere in pausa il giardino?\n\nLa tua pianta non appassirà per 7 giorni.\nUtile quando hai bisogno di una pausa dall\'app.')){pauseGarden(7);}}
const taskCategories={studio:['studiare','esame','lezione','compiti','tesi','scuola','università','corso','materia','storia','matematica','fisica','chimica'],lavoro:['email','meeting','report','progetto','chiamata','lavoro','riunione','presentazione','deadline','documento','cliente'],casa:['pulizie','pulire','lavare','stirare','cucinare','spesa','casa','cucina','bagno','camera','stanza','piatti','biancheria','bucato'],sociale:['uscire','amici','festa','compleanno','chiamare','sociale','cena','aperitivo','evento','appuntamento'],cura:['doccia','vestirsi','medicine','dentista','sport','palestra','correre','yoga','meditare','dormire'],admin:['bollette','banca','documenti','tasse','prenotare','email','modulo','pratica','appuntamento','telefonata']};
function detectTaskCategory(taskName){const t=taskName.toLowerCase();for(const[cat,keywords]of Object.entries(taskCategories)){if(keywords.some(k=>t.includes(k)))return cat;}return 'altro';}
function normalizeTaskName(name){return name.toLowerCase().trim().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');}
function updateTaskDatabase(taskName,category,feeling,trigger,intensity,strategyUsed,completed){if(!taskName)return;const taskId=normalizeTaskName(taskName);if(!state.tasks[taskId]){state.tasks[taskId]={name:taskName,category:category,firstSeen:new Date().toISOString(),lastMentioned:new Date().toISOString(),timesBlocked:0,timesResolved:0,feelings:{},triggers:{},strategies:{},avgIntensity:0,totalIntensity:0,count:0};}const task=state.tasks[taskId];task.lastMentioned=new Date().toISOString();task.count++;task.totalIntensity+=intensity;task.avgIntensity=(task.totalIntensity/task.count).toFixed(1);task.timesBlocked++;if(completed)task.timesResolved++;task.feelings[feeling]=(task.feelings[feeling]||0)+1;task.triggers[trigger]=(task.triggers[trigger]||0)+1;if(strategyUsed){if(!task.strategies[strategyUsed])task.strategies[strategyUsed]={used:0,completed:0};task.strategies[strategyUsed].used++;if(completed)task.strategies[strategyUsed].completed++;}saveState();}
function getBestStrategyForTask(taskId){const task=state.tasks[taskId];if(!task||!task.strategies)return null;let best=null;let bestRate=0;for(const[stratName,stats]of Object.entries(task.strategies)){if(stats.used<2)continue;const rate=stats.completed/stats.used;if(rate>bestRate){bestRate=rate;best={name:stratName,rate:rate,used:stats.used};}}return best;}

// Personal Insights & Adaptive Learning Functions
function getPersonalStrategyStats(){
  const stats={};
  state.history.forEach(h=>{
    if(h.strategyUsed){
      if(!stats[h.strategyUsed])stats[h.strategyUsed]={used:0,completed:0};
      stats[h.strategyUsed].used++;
      if(h.strategyCompleted)stats[h.strategyUsed].completed++;
    }
  });
  return Object.entries(stats)
    .filter(([,s])=>s.used>=2)
    .map(([name,s])=>({name,used:s.used,completed:s.completed,rate:s.completed/s.used}))
    .sort((a,b)=>b.rate-a.rate||b.used-a.used);
}

function updateMainButton(){const emojiEl=document.getElementById('mainGardenEmoji');const levelEl=document.getElementById('mainGardenLevel');const pointsEl=document.getElementById('mainGardenPoints');const progressEl=document.getElementById('mainGardenProgressFill');const pauseBtn=document.getElementById('gardenPauseBtn');if(!emojiEl||!levelEl||!pointsEl||!pauseBtn)return;const isWithered=checkGardenDecay();const level=getGardenLevel(state.garden.points);const emoji=getGardenEmoji(level,isWithered&&!state.garden.isPaused);const name=getGardenName(level);const points=state.garden.points;const levelPoints=[0,21,51,101,201,500];const nextLevel=Math.min(level+1,5);const pointsToNext=levelPoints[nextLevel];const prevLevelPoints=levelPoints[level];const progressInLevel=points-prevLevelPoints;const pointsNeededForLevel=pointsToNext-prevLevelPoints;const progressPercent=level>=5?100:Math.min(100,(progressInLevel/pointsNeededForLevel)*100);emojiEl.textContent=emoji;levelEl.textContent='Lv '+level+' • '+name;pointsEl.textContent=level>=5?points+' punti • Livello massimo!':points+' / '+pointsToNext+' punti al prossimo livello';if(progressEl)progressEl.style.width=progressPercent+'%';if(state.garden.isPaused){pauseBtn.textContent='▶️';pauseBtn.onclick=(e)=>{e.stopPropagation();resumeGarden();};}else{pauseBtn.textContent='⏸️';pauseBtn.onclick=(e)=>{e.stopPropagation();showGardenPauseModal();};}}
function updateHomeStats(){const streakEl=document.getElementById('statStreak');const totalEl=document.getElementById('statTotal');if(!streakEl||!totalEl)return;const streak=calculateStreak();const total=state.history.length;streakEl.textContent=streak;totalEl.textContent=total;}
function calculateStreak(){if(state.history.length===0)return 0;const sortedHistory=[...state.history].sort((a,b)=>new Date(b.date)-new Date(a.date));let streak=0;let currentDate=new Date();currentDate.setHours(0,0,0,0);for(const entry of sortedHistory){const entryDate=new Date(entry.date);entryDate.setHours(0,0,0,0);const diffDays=Math.floor((currentDate-entryDate)/(1000*60*60*24));if(diffDays===streak||diffDays===streak+1){if(diffDays===streak+1)streak++;currentDate=new Date(entryDate);}else{break;}}return streak;}
function updateHomeInsights(){const previewEl=document.getElementById('homeInsightsPreview');const listEl=document.getElementById('homeInsightsList');if(!previewEl||!listEl)return;const insights=getPersonalInsights();if(!insights||state.history.length<3){previewEl.style.display='none';return;}previewEl.style.display='block';let html='';if(insights.recentSuccess){const perc=Math.round(insights.recentSuccess.rate*100);const emoji=perc>=70?'🎉':perc>=50?'💪':'📈';html+='<div class="home-insight-item"><span class="home-insight-emoji">'+emoji+'</span><span>'+perc+'% di successo negli ultimi 7 giorni</span></div>';}if(insights.bestFeeling&&insights.bestFeeling.count>=2){html+='<div class="home-insight-item"><span class="home-insight-emoji">⭐</span><span>Per te funziona quando ti senti '+feelings.find(f=>f.id===insights.bestFeeling.feeling)?.label.toLowerCase()+'</span></div>';}if(insights.temporalPatterns&&insights.temporalPatterns.bestDay){const days=['domenica','lunedì','martedì','mercoledì','giovedì','venerdì','sabato'];html+='<div class="home-insight-item"><span class="home-insight-emoji">📅</span><span>Il tuo giorno migliore: '+days[insights.temporalPatterns.bestDay.day]+'</span></div>';}listEl.innerHTML=html||'<div class="home-insight-item"><span class="home-insight-emoji">✨</span><span>Continua così per sbloccare insights personalizzati!</span></div>';}
function updateHomeScreen(){setGreeting();updateMainButton();updateHomeStats();updateHomeInsights();}
function toggleFabMenu(){const menu=document.getElementById('fabMenu');if(!menu)return;menu.classList.toggle('open');}
function showGardenPauseModal(){if(confirm('Vuoi mettere in pausa il giardino?\n\nLa tua pianta non appassirà per 7 giorni.\nUtile quando hai bisogno di una pausa dall\'app.')){pauseGarden(7);}}
const taskCategories={studio:['studiare','esame','lezione','compiti','tesi','scuola','università','corso','materia','storia','matematica','fisica','chimica'],lavoro:['email','meeting','report','progetto','chiamata','lavoro','riunione','presentazione','deadline','documento','cliente'],casa:['pulizie','pulire','lavare','stirare','cucinare','spesa','casa','cucina','bagno','camera','stanza','piatti','biancheria','bucato'],sociale:['uscire','amici','festa','compleanno','chiamare','sociale','cena','aperitivo','evento','appuntamento'],cura:['doccia','vestirsi','medicine','dentista','sport','palestra','correre','yoga','meditare','dormire'],admin:['bollette','banca','documenti','tasse','prenotare','email','modulo','pratica','appuntamento','telefonata']};
function detectTaskCategory(taskName){const t=taskName.toLowerCase();for(const[cat,keywords]of Object.entries(taskCategories)){if(keywords.some(k=>t.includes(k)))return cat;}return 'altro';}
function normalizeTaskName(name){return name.toLowerCase().trim().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');}
function updateTaskDatabase(taskName,category,feeling,trigger,intensity,strategyUsed,completed){if(!taskName)return;const taskId=normalizeTaskName(taskName);if(!state.tasks[taskId]){state.tasks[taskId]={name:taskName,category:category,firstSeen:new Date().toISOString(),lastMentioned:new Date().toISOString(),timesBlocked:0,timesResolved:0,feelings:{},triggers:{},strategies:{},avgIntensity:0,totalIntensity:0,count:0};}const task=state.tasks[taskId];task.lastMentioned=new Date().toISOString();task.count++;task.totalIntensity+=intensity;task.avgIntensity=(task.totalIntensity/task.count).toFixed(1);task.timesBlocked++;if(completed)task.timesResolved++;task.feelings[feeling]=(task.feelings[feeling]||0)+1;task.triggers[trigger]=(task.triggers[trigger]||0)+1;if(strategyUsed){if(!task.strategies[strategyUsed])task.strategies[strategyUsed]={used:0,completed:0};task.strategies[strategyUsed].used++;if(completed)task.strategies[strategyUsed].completed++;}saveState();}
function getBestStrategyForTask(taskId){const task=state.tasks[taskId];if(!task||!task.strategies)return null;let best=null;let bestRate=0;for(const[stratName,stats]of Object.entries(task.strategies)){if(stats.used<2)continue;const rate=stats.completed/stats.used;if(rate>bestRate){bestRate=rate;best={name:stratName,rate:rate,used:stats.used};}}return best;}

// Personal Insights & Adaptive Learning Functions
function getPersonalStrategyStats(){
  const stats={};
  state.history.forEach(h=>{
    if(h.strategyUsed){
      if(!stats[h.strategyUsed])stats[h.strategyUsed]={used:0,completed:0};
      stats[h.strategyUsed].used++;
      if(h.strategyCompleted)stats[h.strategyUsed].completed++;
    }
  });
  return Object.entries(stats)
    .filter(([,s])=>s.used>=2)
    .map(([name,s])=>({name,used:s.used,completed:s.completed,rate:s.completed/s.used}))
    .sort((a,b)=>b.rate-a.rate||b.used-a.used);
}

function showGardenPauseModal(){if(confirm('Vuoi mettere in pausa il giardino?\n\nLa tua pianta non appassirà per 7 giorni.\nUtile quando hai bisogno di una pausa dall\'app.')){pauseGarden(7);}}
const taskCategories={studio:['studiare','esame','lezione','compiti','tesi','scuola','università','corso','materia','storia','matematica','fisica','chimica'],lavoro:['email','meeting','report','progetto','chiamata','lavoro','riunione','presentazione','deadline','documento','cliente'],casa:['pulizie','pulire','lavare','stirare','cucinare','spesa','casa','cucina','bagno','camera','stanza','piatti','biancheria','bucato'],sociale:['uscire','amici','festa','compleanno','chiamare','sociale','cena','aperitivo','evento','appuntamento'],cura:['doccia','vestirsi','medicine','dentista','sport','palestra','correre','yoga','meditare','dormire'],admin:['bollette','banca','documenti','tasse','prenotare','email','modulo','pratica','appuntamento','telefonata']};
function detectTaskCategory(taskName){const t=taskName.toLowerCase();for(const[cat,keywords]of Object.entries(taskCategories)){if(keywords.some(k=>t.includes(k)))return cat;}return 'altro';}
function normalizeTaskName(name){return name.toLowerCase().trim().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');}
function updateTaskDatabase(taskName,category,feeling,trigger,intensity,strategyUsed,completed){if(!taskName)return;const taskId=normalizeTaskName(taskName);if(!state.tasks[taskId]){state.tasks[taskId]={name:taskName,category:category,firstSeen:new Date().toISOString(),lastMentioned:new Date().toISOString(),timesBlocked:0,timesResolved:0,feelings:{},triggers:{},strategies:{},avgIntensity:0,totalIntensity:0,count:0};}const task=state.tasks[taskId];task.lastMentioned=new Date().toISOString();task.count++;task.totalIntensity+=intensity;task.avgIntensity=(task.totalIntensity/task.count).toFixed(1);task.timesBlocked++;if(completed)task.timesResolved++;task.feelings[feeling]=(task.feelings[feeling]||0)+1;task.triggers[trigger]=(task.triggers[trigger]||0)+1;if(strategyUsed){if(!task.strategies[strategyUsed])task.strategies[strategyUsed]={used:0,completed:0};task.strategies[strategyUsed].used++;if(completed)task.strategies[strategyUsed].completed++;}saveState();}
function getBestStrategyForTask(taskId){const task=state.tasks[taskId];if(!task||!task.strategies)return null;let best=null;let bestRate=0;for(const[stratName,stats]of Object.entries(task.strategies)){if(stats.used<2)continue;const rate=stats.completed/stats.used;if(rate>bestRate){bestRate=rate;best={name:stratName,rate:rate,used:stats.used};}}return best;}

// Personal Insights & Adaptive Learning Functions
function getPersonalStrategyStats(){
  const stats={};
  state.history.forEach(h=>{
    if(h.strategyUsed){
      if(!stats[h.strategyUsed])stats[h.strategyUsed]={used:0,completed:0};
      stats[h.strategyUsed].used++;
      if(h.strategyCompleted)stats[h.strategyUsed].completed++;
    }
  });
  return Object.entries(stats)
    .filter(([,s])=>s.used>=2)
    .map(([name,s])=>({name,used:s.used,completed:s.completed,rate:s.completed/s.used}))
    .sort((a,b)=>b.rate-a.rate||b.used-a.used);
}

export { checkGardenDecay, getGardenLevel, getGardenEmoji, getGardenName, addGardenPoints, pauseGarden, resumeGarden, updateGardenBadge, updateMainButton, showGardenPauseModal };
